version: 0.0
os: linux
files:
  - source: /path/to/index.html
    destination: /var/www/html/index.html
  - source: /path/to/result.html
    destination: /var/www/html/result.html
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root